[package]
name = "aoc_7_1"
version = "0.1.0"
authors = ["fluffybled <bledarkabashaj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
